# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='codigo_postal',
            new_name='Codigo_postal',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='timestamp',
            new_name='Timestamp',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='formulario',
            name='Asunto',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='Mensaje',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
