# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-24 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20160928_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='Codigo_postal',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='Timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
